apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-app
spec:
  selector:
    matchLabels:
      app: api-gateway-app
  template:
    metadata:
      labels:
        app: api-gateway-app
    spec:
      containers:
      - name: api-gateway-app
        image: ngochung1809/api-gateway:0.0.1
        ports:
        - containerPort: 8080
        env:
          - name: EUREKA_SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                key: eureka_server_address
                name: eureka-cm
          - name: CONFIG_URL
            valueFrom:
              configMapKeyRef:
                key: config_url
                name: config-cm
          - name: ZIPKIN_URL
            valueFrom:
              configMapKeyRef:
                key: zipkin_url
                name: zipkin-cm

---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway-svc
spec:
  type: LoadBalancer
  selector:
    app: api-gateway-app
  ports:
  - port: 80
    targetPort: 8080

