apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
data:
  eureka_server_address: "http://eureka-0.eureka:8000/eureka"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
data:
  config_url: "http://config-server-svc"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cm
data:
  db_host: "mysql-0.mysql"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: zipkin-cm
data:
  zipkin_url: "http://zipkin-svc:9411"

# redis:
#   host: ${REDIS_HOST:localhost}
#   port: ${REDIS_PORT:6379}