apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-app
spec:
  selector:
    matchLabels:
      app: order-service-app
  template:
    metadata:
      labels:
        app: order-service-app
    spec:
      containers:
      - name: order-service-app
        image: ngochung1809/order-service:0.0.1
        ports:
        - containerPort: 8081
        env:
          - name: EUREKA_SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                key: eureka_server_address
                name: eureka-cm
          - name: CONFIG_URL
            valueFrom:
              configMapKeyRef:
                key: config_url
                name: config-cm
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                key: db_host
                name: mysql-cm
          - name: ZIPKIN_URL
            valueFrom:
              configMapKeyRef:
                key: zipkin_url
                name: zipkin-cm
---

apiVersion: v1
kind: Service
metadata:
  name: order-service-svc
spec:
  selector:
    app: order-service-app
  ports:
  - port: 80
    targetPort: 8081
